// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyTesztsHxF8nAhwn58bQXVQNlxu_81sw',
    appId: '1:1087476016128:android:205d7e6d4db6b7fb6824e5',
    messagingSenderId: '1087476016128',
    projectId: 'evently-app-45362',
    storageBucket: 'evently-app-45362.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMxV4QFLkEEkgYSdAChBajEhA0PLbiQnc',
    appId: '1:1087476016128:ios:30d50962f9220e6e6824e5',
    messagingSenderId: '1087476016128',
    projectId: 'evently-app-45362',
    storageBucket: 'evently-app-45362.firebasestorage.app',
    androidClientId: '1087476016128-52nr4o7oeshksea4t9jrv3genf4hv6ap.apps.googleusercontent.com',
    iosClientId: '1087476016128-nl9q14tuaffthmuelkqjer9ts9dr2ff9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventlyApp',
  );

}